---
result: FAILURE
failure_category: unknown
failure_cause: unknown
timestamp: 2016-06-22 22:18:27 UTC
url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/235/
trigger_url: http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/382/
duration: 2m34s
logs:
  consoleText:
    5605: |2

      WARNING: No knife configuration file found
      ERROR: LocalJumpError: unexpected return
    5612: |
      .......

      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-config-12.12.4/lib/chef-config/config.rb:522:in `block in <class:Config>': unexpected return (LocalJumpError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-config-2.2.1/lib/mixlib/config/configurable.rb:48:in `call'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-config-2.2.1/lib/mixlib/config/configurable.rb:48:in `get'
    5631: |2

      WARNING: No knife configuration file found
      ERROR: LocalJumpError: unexpected return
    5662: |2


      ....../opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:289:in `invalid!': Expected process to exit with [0], but received '100' (Mixlib::ShellOut::ShellCommandFailed)
      ---- Begin output of /usr/bin/knife exec -E true ----
      STDOUT:
      STDERR: WARNING: No knife configuration file found
      ERROR: LocalJumpError: unexpected return
      ---- End output of /usr/bin/knife exec -E true ----
      Ran /usr/bin/knife exec -E true returned 100
    5677: |2
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.16.1/lib/chef-dk/component_test.rb:99:in `run_smoke_test'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.16.1/lib/chef-dk/command/verify.rb:580:in `block (2 levels) in invoke_tests'
      Build step 'Invoke XShell command' marked build as failure
      Archiving artifacts
      Recording fingerprints
