---
result: FAILURE
url: http://wilson.ci.chef.co/job/chef-server-12-fips-trigger-ad_hoc/6/
failure_category: unknown
failure_cause: 'unknown: all: chef-server-12-fips-test'
timestamp: 2015-12-28 22:51:34 UTC
duration: 39m22s
triggered_by: jaym
active_duration: 39m6s
queue_delays: 10s
parameters:
  GIT_REF: jdm/fips-final
  EXPIRE_CACHE: false
change:
  git_remote: git@github.com:chef/chef-server.git
  git_commit: 8a162b31631d5d5d9818a492f1abfe0eb29f3a12
  project: chef-server-fips
  version: 12.3.1+20151228225151
stages:
  chef-server-12-fips-test:
    result: FAILURE
    failure_category: unknown
    failure_cause: 'unknown: all'
    url: http://wilson.ci.chef.co/job/chef-server-12-fips-test/6/
    duration: 12m6s
    runs:
      el-6:
        result: FAILURE
        failure_category: unknown
        failure_cause: unknown
        url: http://wilson.ci.chef.co/job/chef-server-12-fips-test/architecture=x86_64,platform=el-6,project=chef-server-fips,role=tester/6/
        duration: 12m5s
        logs:
          consoleText:
            2408: |
              No entry for terminal type "unknown";
              using dumb terminal settings.
              /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/core_ext/net_http.rb:22:in `initialize': Connection refused - connect(2) for "ip-10-194-14-246.us-west-2.compute.internal" port 443 (Errno::ECONNREFUSED)
                from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/core_ext/net_http.rb:22:in `open'
                from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/core_ext/net_http.rb:22:in `block in connect'
            2435: |
              Configured URL: https://ip-10-194-14-246.us-west-2.compute.internal
              Creating org pedant_testorg_ip-10-194-14-246_13748
              Build step 'Invoke XShell command' marked build as failure
              Performing Post build task...
              Match found for : : True
            2456: |
              Recording fingerprints
              Recording test results
              ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to exception
              hudson.AbortException: No test report files were found. Configuration error?
                at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:116)
                at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:92)
                at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2688)
                at hudson.remoting.UserRequest.perform(UserRequest.java:121)
                at hudson.remoting.UserRequest.perform(UserRequest.java:49)
                at hudson.remoting.Request$2.run(Request.java:325)
                at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
                at java.util.concurrent.FutureTask.run(FutureTask.java:262)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at java.lang.Thread.run(Thread.java:745)
                at ......remote call to chef-server-fips-rhel-6-tester-638911(Native Method)
                at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1360)
                at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
                at hudson.remoting.Channel.call(Channel.java:753)
                at hudson.FilePath.act(FilePath.java:978)
                at hudson.FilePath.act(FilePath.java:967)
                at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:89)
                at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:121)
                at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:138)
                at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
                at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
                at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
                at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
                at hudson.model.Build$BuildExecution.post2(Build.java:183)
                at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
                at hudson.model.Run.execute(Run.java:1766)
                at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
                at hudson.model.ResourceController.execute(ResourceController.java:98)
                at hudson.model.Executor.run(Executor.java:374)
              [BFA] Scanning build for known causes...
              [BFA] No failure causes found
        steps:
          total: 12m5s
          before (setup time): 2m51s
          chef-client private-chef::default: 7m22s
          after (cleanup time): 1m51s
  chef-server-12-fips-build:
    result: SUCCESS
    url: http://wilson.ci.chef.co/job/chef-server-12-fips-build/9/
    duration: 26m54s
    queue_delay: 10s
    runs:
      el-6:
        result: SUCCESS
        url: http://wilson.ci.chef.co/job/chef-server-12-fips-build/architecture=x86_64,platform=el-6,project=chef-server-fips,role=builder/9/
        duration: 26m34s
  chef-server-12-fips-trigger-ad_hoc:
    result: SUCCESS
    url: http://wilson.ci.chef.co/job/chef-server-12-fips-trigger-ad_hoc/6/
    duration: 6s
